---
title: "TitanicAnalysis"
author: "AmyHs , slimykat , Rabbit55"
date: "2018年5月2日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#套件包
```{r}
library(ggplot2)
library(e1071)
library(knitr)
```

#資料
```{r}
train<-read.csv("titanicTrain.csv")
train<-train[-c(1001:1310),]
quest<-read.csv("titanicQuestion.csv")
all<-rbind(train,quest)
```

#資料缺失量
```{r}
is_na<-function(x){
  sum(is.na(x))
}
sapply(train,is_na)
sapply(quest,is_na)
```

#資料探索
##0.1資料轉換
```{r}
all$survived<-as.factor(all$survived)
all$pclass<-as.ordered(all$pclass)
```

##0.2性別與死亡
```{r}
ggplot(all[!is.na(all$survived),], aes(x = sex, fill = survived)) +
  geom_bar(stat='count', position='dodge') + theme_grey() +
  labs(x = 'alling data only') +
  geom_label(stat='count', aes(label=..count..))
```

##0.3死亡與pclass
###0.3.1 class與死亡
```{r}
ggplot(all[!is.na(all$survived),], aes(x = pclass, fill = survived)) +
  geom_bar(stat='count', position='dodge') + labs(x = 'alling data only') +
  theme(legend.position="none") 
```

###0.3.2 class& sex &死亡
```{r}
ggplot(all[!is.na(all$survived),], aes(x = pclass, fill = survived)) +
  geom_bar(stat='count', position='fill') +
  labs(x = 'alling data only', y= "Percent") + facet_grid(.~sex) 
```

##0.4 fare&死亡
```{r}
all[all$fare==0,]
#發現有class1中fare=0的人很多，好像票價跟階級或年齡的直接關聯看不出來
ggplot(all[!is.na(all$survived),], aes(x = fare, fill = survived)) +
  geom_histogram( bins= 30) +
  labs(x = 'alling data only', y= "Count") + facet_grid(.~pclass)
#看不出什麼結果
```

##0.5 缺失值處理
###0.5.1先解決boat的缺失值
```{r}
all$boat = as.numeric(all$boat != "")
```

###0.5.2用現有資料預測年紀的缺失值
```{r}
agelm <- lm(age ~ pclass+boat+sex+parch+sibsp, data=all[!is.na(all$age),])
#看一下哪一項預測力較好，以及R^2值
summary(agelm)
all$agelm<-predict(agelm,all)
```

###0.5.3預測結果比較
```{r}
hist(all$age[!is.na(all$age)], main='Original data, non-missing', xlab='age')
hist(all$agelm, main= 'LM predictions', xlab='age', xlim=range(0:80))
```

###0.5.4將缺失值補齊
```{r}
indexMissingAge <- which(is.na(all$age))
all$age[indexMissingAge] <- all$agelm[indexMissingAge]

fare_NAindex = which(is.na(all$fare))
#發現持有3701號票根的客人在fare factor處有na
temp = all$fare[nchar( as.character(all$ticket)) == 4 & grepl("^3",as.character(all$ticket))]
average = sum(temp[!is.na(temp)])/(length(temp)-1)
all[fare_NAindex,"fare"] = average
#將類似票根號的票價取平均

#將資料拆分成四個區塊
female_insea = all[all$sex == "female" & all$boat == 0,c("age","fare","survived")]
female_onboat = all[all$sex == "female" & all$boat == 1,c("age","fare","survived")]
male_insea = all[all$sex == "male" & all$boat == 0,c("age","fare","survived")]
male_onboat = all[all$sex == "male" & all$boat == 1,c("age","fare","survived")]

female_insea[,3] = as.factor(female_insea[,3])
female_onboat[,3] = as.factor(female_onboat[,3])
male_insea[,3] = as.factor(male_insea[,3])
male_onboat[,3] = as.factor(male_onboat[,3])

#對fare取log10減少數據偏移
female_insea[,2] = log10(female_insea[,2])
female_onboat[,2] = as.factor(female_onboat[,2])
male_insea[,2] = as.factor(male_insea[,2])
male_onboat[,2] = as.factor(male_onboat[,2])
```

##0.5 SVM
```{r}
#分別對每個區塊做SVM

plot_svm <- function(dat){
  survived = as.numeric(dat[,3])
  all_index = !is.na(survived)
  svmfit = svm(survived[all_index] ~ ., data = dat[all_index,], cost = 100)
  return(svmfit)
}
par(mfrow=c(2,2))

svm1 = plot_svm(female_insea)
#plot(temp,female_insea[!is.na(female_insea$survived),])
svm2 = plot_svm(female_onboat)
# plot(temp,female_onboat[!is.na(female_onboat$survived),])
svm3 = plot_svm(male_insea)
# plot(temp,male_insea[!is.na(male_insea$survived),])
svm4 = plot_svm(male_onboat)
# plot(temp,male_onboat[!is.na(male_onboat$survived),])

outcome1 = data.frame(predict(svm1,female_insea[is.na(female_insea$survived),c(1:2)]))
outcome2 = data.frame(predict(svm2,female_onboat[is.na(female_onboat$survived),c(1:2)]))
outcome3 = data.frame(predict(svm3,male_insea[is.na(male_insea$survived),c(1:2)]))
outcome4 = data.frame(predict(svm4,male_onboat[is.na(male_onboat$survived),c(1:2)]))

#合併結果進行輸出
names(outcome1) = "y"
names(outcome2) = "y"
names(outcome3) = "y"
names(outcome4) = "y"

ans = rbind(outcome1,outcome2,outcome3,outcome4)
index = order(row.names(ans))
ans = ans[index,]
write.csv(ans,file="titanicPrediction.csv")

kable(table(ans))
```

