---
title: "project5--keras"
author: "Rabbit55, slimmycat, AmyHs"
date: "2018年5月31日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r cars}
#Preparing the data
#install keras packages
#Before that, one has to update r to r3.5.0 and download Anacondo
library(keras)
install_keras()
#Since the MNIST is included in keras, we tried tried MNIST database to do out five project.
#create variables for the train and test data
mnist <- dataset_mnist()
x_train <- mnist$train$x
y_train <- mnist$train$y
x_test <- mnist$test$x
y_test <- mnist$test$y
#reshape
#change the x data from 3 dimensions to a 28X28 matrix.
x_train <- array_reshape(x_train, c(nrow(x_train), 784))
x_test <- array_reshape(x_test, c(nrow(x_test), 784))
#rescale
#converge the value of x from 1~255 to 0~1
#transform hte y data from an interger array into binary matrixes
x_train <- x_train / 255
x_test <- x_test / 255
y_train <- to_categorical(y_train, 10)
y_test <- to_categorical(y_test, 10)

#definig the model
#the structure of keras is a model with layers. We first create a model and then add some layers.
model <- keras_model_sequential() 
model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')
summary(model)

#compile the model with loss, optimizer, and metrics functions
model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)

#Training and Evaluation
#train the model for 30 epochs using batches of 128 images
history <- model %>% fit(
  x_train, y_train, 
  epochs = 30, batch_size = 128, 
  validation_split = 0.2
)
plot(history)
#Evaluate the model’s performance on the test data
model %>% evaluate(x_test, y_test)
#Generate a prediction on new data
model %>% predict_classes(x_test)

```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
